version: "3.7"

# Build the GitWrite (dev branch) with NERVE tool included in the same stack

services:
  traefik:
    container_name: traefik
    image: traefik:v2.4
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 443:443
    networks:
      - cwrc-gitwriter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./container_volumes/traefik/:/etc/traefik
      - ./container_volumes/letsencrypt:/var/letsencrypt/
      - ./container_volumes/traefik/log/:/var/log/traefik
    restart: unless-stopped

  gitserver:
    container_name: gitserver
    image: cwrc/cwrc-gitserver:latest
    volumes:
      - ./container_volumes/cwrc-gitserver/config/:/apps/CWRC-GitServer/config/
    networks:
      - cwrc-gitwriter
    restart: unless-stopped

  gitwriter:
    container_name: gitwriter
    image: cwrc/cwrc-gitwriter:latest
    volumes:
      - ./container_volumes/cwrc-gitwriter/config/:/apps/CWRC-GitWriter/build/config/
    networks:
      - cwrc-gitwriter
    restart: unless-stopped

  validator:
    container_name: validator
    image: cwrc/cwrc-validator:latest
    volumes:
      - ./container_volumes/validator/:/usr/local/tomcat/logs
    networks:
      - cwrc-gitwriter
    restart: unless-stopped

  nerve:
    container_name: nerve
    image: registry.gitlab.com/calincs/conversion/nssi:latest
    environment:
      - LOG_LEVEL=VERBOSE # Log4J Logging level: WARN, VERBOSE
    volumes:
      - ./container_volumes/nerve/:/usr/local/tomcat/logs
    networks:
      - cwrc-gitwriter
    restart: unless-stopped

  # optional: poll DockerHub and update if image changes
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command:
      - --cleanup
      - --interval=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  cwrc-gitwriter:
